### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sebasfiorent** [0k/web_m2o_enhanced#1] opened 2013-05-30 13:22 UTC
Hi. First of all, great initiative!
I've downloaded and installed this addon, but I can get it working under default mode, ie. for Human Resources Employee an employee doesn't have permissions to create or edit leave types. But the Leave type selection always shows the Create Edit option. Any suggestion?

**Comment by njeudy** [comment] 2013-06-11 08:44
I create a test database from scratch, if user is only HR employee, leave type does'nt show create an edit option. I add and screenshot of form I have.

![img1](https://f.cloud.github.com/assets/995787/636055/e64801e2-d272-11e2-8d3b-fade10a5f8cf.png)

i close this issue because I can not reproduce it. feel free to reopen one and give us a dump or an access to your database to check it !

**Comment by njeudy** [comment] 2013-06-11 08:44
closed

**Closed as completed by njeudy** 2013-06-11 08:44 UTC
Labels: invalid
